apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx
  name: mynginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-tomcat
  name: nginx-tomcat
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: tomcat
    image: tomcat:9.0.55
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-tomcat
  name: nginx-tomcat
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: tomcat
    image: tomcat
